version: "3"
services:
  mongo-prod:
    container_name: mongo-prod
    image: mongo:latest
    ports:
      - "20717:20717"
    volumes:
      - /data/db # Create a volume for the DB.
  client-prod:
    container_name: client-prod
    build:
      context: ./client
      dockerfile: Dockerfile
      args: # We need to use arguments to pass env variables defined in client.prod.env passed as --env-file argument in docker compose command to be used during the docker image build.
        NODE_ENV_ARG: ${NODE_ENV}
        API_URL_ARG: ${API_URL}
        NODE_PATH_ARG: ${NODE_PATH}
    ports:
      - "3000:3000"
    restart: always
  server-prod:
    container_name: client-prod
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongo-prod
    env_file:
      - server.prod.env # Thise are runtime env variables that do not require to be used during docker image build.
    ports:
      - "8081:8081"
    restart: always
